### ISSUE TITLE
No Data In Grafana Dashboard

### ISSUE THREAD

**Issue by stephenstubbs** [yugabyte/charts#20]
Hi,

I've installed the chart with `serviceMonitor.enabled: true` and can see the service monitor has been added. Then I've added this dashboard to grafana https://grafana.com/grafana/dashboards/12528 however it shows no data. Any ideas why this might be happening?

**Comment by kmuthukk** [comment]
@iSignal , @bhavin192 ^^ thoughts?

**Comment by bhavin192** [comment]
Can you please try this dashboard? https://grafana.com/grafana/dashboards/12620
Our plan was to merge these two into one.

**Comment by stephenstubbs** [comment]
This one works well thanks.

**Comment by iSignal** [comment]
@sstubbs : nice!
