### ISSUE TITLE
Upgrade Chart In Repo to 2.1.6

### ISSUE THREAD

**Issue by stephenstubbs** [yugabyte/charts#4]
Hi,

I've just installed yugabyte db from the repo and only see 2.1.5 as a version. By running `helm search repo yugabytedb/yugabyte` I get

```
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                                       
yugabytedb/yugabyte	2.1.5        	2.1.5.0-b17	YugabyteDB is the high-performance distributed ...
```

**Comment by iSignal** [comment]
Thanks @sstubbs  for reporting this. @Arnav15 is working on synchronizing the github charts repo with charts.yugabyte.com and should have an update shortly.

**Comment by iSignal** [comment]
@sstubbs : charts repo is now at 2.1.6.0. Please update the helm repo and try again.
