### ISSUE TITLE
tls does not seem to be working

### ISSUE THREAD

**Issue by stephenstubbs** [yugabyte/charts#5]
Perhaps I'm doing something wrong but if tls is enabled in the chart and I try connect to it like the following:
```
ysqlsh "sslmode=require host=XXX.XXX.X.XXX dbname=yugabyte"
```
I get the following error:
```
ysqlsh: server does not support SSL, but SSL was required
```

**Comment by iSignal** [comment]
@sstubbs : Thanks for reporting this. I am going to move this issue to the main repo at https://github.com/yugabyte/yugabyte-db/issues/4682.
