### ISSUE TITLE
New Chart release

### ISSUE THREAD

**Issue by VictorBac** [yugabyte/charts#68]
Hi guys,

This PR fixed a problem with the busybox image being hardcoded:
https://github.com/yugabyte/charts/pull/54

But when I pull the chart from the helm repo I still have the old busybox image.

Is it possible to create a new release of the chart ? When will it be available ?

If I create a PR to update the version in Chart.yaml to 2.7.1, will it automatically create a new release ?

Thank you.

**Comment by jvigil-yugabyte** [comment]
@VictorBac we are planning to make a new release early next week, which should include the change you linked.
