### ISSUE TITLE
Disable `callhome`

### ISSUE THREAD

**Issue by samstride** [yugabyte/charts#92]
Hi,

Thanks for maintaining this repo.

- Is there any documentation regarding the type of data that is collected? I tried a google search + search on the docs website but don't think I found anything.
- Is there a way to disable `callhome` via the helm chart?

Cheers

**Comment by iSignal** [comment]
https://docs.yugabyte.com/latest/manage/diagnostics-reporting/ has more docs on diagnostics reporting. It also suggests flags that you can set to control this. Those flags would be passed in to the helm chart via `gflags.master` and `gflags.tserver` at https://github.com/yugabyte/charts/blob/0b8b2d20d557e40bb35e71431c0088e933d57825/stable/yugabyte/values.yaml#L56

**Comment by samstride** [comment]
@iSignal , thanks for the response.

We want to change the `callhome_collection_level` to low on an existing installation and we are running into this error:

```sh
helm list -n yugabyte                                                       

NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
yugabyte                yugabyte        1               2021-09-22 17:48:21.562119 +1200 NZST   deployed        yugabyte-2.9.0                          2.9.0.0-b4 
yugabyte-nfs-client     yugabyte        1               2021-09-22 17:33:20.138329 +1200 NZST   deployed        nfs-subdir-external-provisioner-4.0.13  4.0.2

helm upgrade yugabyte yugabytedb/yugabyte -n yugabyte \
  --set gflags.master.callhome_collection_level=low \
  --set gflags.tserver.callhome_collection_level=low \
  --dry-run
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Service "yb-tserver-service" in namespace "yugabyte" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "yugabyte"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "yugabyte"
```

Can the collection level be changed after installation or did I miss something in my helm upgrade command?

Cheers.

**Comment by iSignal** [comment]
That error doesn't seem related to the gflags setting. It seems like a general helm issue. Can you this out on a fresh install in a different namespace? (helm install followed by the helm upgrade command you referenced)

**Comment by samstride** [comment]
@iSignal , thanks. I figured out a way to work around that error.

```sh
helm get values yugabyte -n yugabyte > yugabyte.yaml

helm upgrade yugabyte yugabytedb/yugabyte -n yugabyte \
  -f yugabyte.yaml \
  --set gflags.master.callhome_collection_level=low \
  --set gflags.tserver.callhome_collection_level=low
```

Working now. Thanks for the assist. Closing issue.

We have recently started using Yugabyte (moving from postgres) and it's been ok so far.

Cheers.
