### ISSUE TITLE
Question: How to change flags in helm charts

### ISSUE THREAD

**Issue by GeroL** [yugabyte/charts#97]
Hi,

I wanted to change the flag async_replication_polling_delay_ms for the tserver instances.
How could that be done? I guess I have to fork the charts and add the flag manually right?

Thanks

**Comment by jvigil-yugabyte** [comment]
Hey, this can be done by setting a tserver gflag key/value pair: https://github.com/yugabyte/charts/blob/3758cc5b6b01f11003f591232cf48ba5f8df4fbe/stable/yugabyte/values.yaml#L79.

Also, we're available on slack to answer any questions as well :)
yugabyte-db.slack.com #topic-kubernetes
